/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tourist;

import java.util.ArrayList;

/**
 *
 * @author khejur
 */
public class FindPath extends javax.swing.JInternalFrame {

    /**
     * Creates new form FindPath
     */
    public FindPath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("National Museum");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Jatiyo Sangsad Bhaban");

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox3.setText("Lalbagh Fort");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox4.setText("Ahsan Manzil");

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox5.setText("Botanical Garden");

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox6.setText("Dhakeshwari Temple");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Enter your Location");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addGap(22, 22, 22)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<User> list = ListUser.getUsers();
        if (jCheckBox1.isSelected()) {
            int[] dis = new int[6];
            Dijkstra.Dijkstra(0, dis);
            jTextArea1.setText("");
            jTextArea1.append("Your Location: \n");
            jTextArea1.append(list.get(0).source);
            jTextArea1.append("\n");
            jTextArea1.append("\nDistance From Your Location: \n");
            for (int i = 0; i < 6; i++) {
                jTextArea1.append("\n" + list.get(i).source + ": " + dis[i]+" km");
            }
        }
        if (jCheckBox2.isSelected()) {
            int[] dis = new int[6];
            Dijkstra.Dijkstra(1, dis);
            jTextArea1.setText("");
            jTextArea1.append("Your Location: \n");
            jTextArea1.append(list.get(1).source);
            jTextArea1.append("\n");
            jTextArea1.append("\nDistance From Your Location: \n");
            for (int i = 0; i < 6; i++) {
                jTextArea1.append("\n" + list.get(i).source + ": " + dis[i]+" km");
            }
        }
        if (jCheckBox3.isSelected()) {
            int[] dis = new int[6];
            Dijkstra.Dijkstra(2, dis);
            jTextArea1.setText("");
            jTextArea1.append("Your Location: \n");
            jTextArea1.append(list.get(2).source);
            jTextArea1.append("\n");
            jTextArea1.append("\nDistance From Your Location: \n");
            for (int i = 0; i < 6; i++) {
                jTextArea1.append("\n" + list.get(i).source + ": " + dis[i]+" km");
            }
        }
        if (jCheckBox4.isSelected()) {
            int[] dis = new int[6];
            Dijkstra.Dijkstra(3, dis);
            jTextArea1.setText("");
            jTextArea1.append("Your Location: \n");
            jTextArea1.append(list.get(3).source);
            jTextArea1.append("\n");
            jTextArea1.append("\nDistance From Your Location: ");
            for (int i = 0; i < 6; i++) {
                jTextArea1.append("\n" + list.get(i).source + ": " + dis[i]+" km");
            }
        }
        if (jCheckBox5.isSelected()) {
            int[] dis = new int[6];
            Dijkstra.Dijkstra(4, dis);
            jTextArea1.setText("");
            jTextArea1.append("Your Location: \n");
            jTextArea1.append(list.get(4).source);
            jTextArea1.append("\n");
            jTextArea1.append("\nDistance From Your Location: ");
            for (int i = 0; i < 6; i++) {
                jTextArea1.append("\n" + list.get(i).source + ": " + dis[i]+" km");
            }
        }
        if (jCheckBox6.isSelected()) {
            int[] dis = new int[6];
            Dijkstra.Dijkstra(5, dis);
            jTextArea1.setText("");
            jTextArea1.append("Your Location: \n");
            jTextArea1.append(list.get(5).source);
            jTextArea1.append("\n");
            jTextArea1.append("\nDistance From Your Location: ");
            for (int i = 0; i < 6; i++) {
                jTextArea1.append("\n" + list.get(i).source + ": " + dis[i]+" km");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
            private ArrayList<User> ListUsers() {
                    // Implement this method to return a list of User objects
                    return new ArrayList<>();
                }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
